export const MAX_LENGTH_PROJECT_NAME = 64
export const MAX_LENGTH_DATA_MODEL_NAME = 64
export const MAX_LENGTH_DATA_MODEL_FIELD_NAME = 64
export const MAX_LENGTH_WORKFLOW_NAME = 64
export const MAX_LENGTH_DATA_MODEL_FIELD_DESCRIPTION = 1024